-- Class PDF materials + text chunks with embeddings (JSON float array for local/Neon without pgvector).

CREATE TABLE IF NOT EXISTS class_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade VARCHAR(16) NOT NULL,
    subject VARCHAR(80) NOT NULL DEFAULT 'GENERAL',
    title VARCHAR(300) NOT NULL,
    original_filename VARCHAR(300),
    storage_path VARCHAR(1024),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    chunk_count INT NOT NULL DEFAULT 0,
    error_message VARCHAR(2000),
    uploaded_by VARCHAR(120),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_class_materials_grade_subject
    ON class_materials (grade, subject);

CREATE TABLE IF NOT EXISTS class_material_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id BIGINT NOT NULL,
    chunk_index INT NOT NULL,
    content TEXT NOT NULL,
    embedding TEXT,
    token_estimate INT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_class_material_chunks_material
        FOREIGN KEY (material_id) REFERENCES class_materials (id) ON DELETE CASCADE,
    CONSTRAINT uq_class_material_chunks_material_idx
        UNIQUE (material_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS idx_class_material_chunks_material
    ON class_material_chunks (material_id);

-- Sidebar menu entry (safe if menus already seeded)
INSERT INTO menu_items (menu_key, label, href, icon, sort_order, enabled_teacher, enabled_admin)
SELECT 'materials', 'Class PDFs', '/teacher/materials', '📄', 45, TRUE, TRUE
WHERE NOT EXISTS (SELECT 1 FROM menu_items WHERE menu_key = 'materials');
