-- Learning teaching conversations (context memory) — additive; does not alter class_materials.

CREATE TABLE IF NOT EXISTS learning_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_username VARCHAR(120) NOT NULL,
    grade VARCHAR(16),
    subject VARCHAR(80),
    material_id BIGINT,
    chapter_title VARCHAR(300),
    language VARCHAR(16) NOT NULL DEFAULT 'auto',
    explanation_level VARCHAR(32) NOT NULL DEFAULT 'simple',
    summary TEXT,
    message_count INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_learning_conversations_teacher_active
    ON learning_conversations (teacher_username, active);

CREATE INDEX IF NOT EXISTS idx_learning_conversations_scope
    ON learning_conversations (teacher_username, grade, subject, material_id, active);

CREATE TABLE IF NOT EXISTS learning_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_learning_messages_conversation
        FOREIGN KEY (conversation_id) REFERENCES learning_conversations (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_learning_messages_conversation_created
    ON learning_messages (conversation_id, created_at);
