-- Flyway-managed schema for role-based menus.

CREATE TABLE IF NOT EXISTS menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_key VARCHAR(80) NOT NULL UNIQUE,
    label VARCHAR(120) NOT NULL,
    href VARCHAR(250) NOT NULL,
    icon VARCHAR(60),
    sort_order INT NOT NULL,
    enabled_teacher BOOLEAN NOT NULL,
    enabled_admin BOOLEAN NOT NULL
);

