-- Audit log for SuperAdmin cleanup actions (who/when/what/how many rows).
CREATE TABLE IF NOT EXISTS cleanup_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_username VARCHAR(120) NOT NULL,
    action_key VARCHAR(80) NOT NULL,
    params_json TEXT,
    deleted_count BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

